//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivestreamingE_commercePlatform.Models
{
    using System;
    using System.Collections.Generic;
    using Volo.Abp.Domain.Entities.Auditing;

    //地址表
    public partial class Address : AuditedAggregateRoot<Guid>
    {
        public Nullable<System.Guid> UserId { get; set; }            //用户Id
        public string Recipient { get; set; }                                      //收件人
        public string RecipientPhone { get; set; }                            //收件人电话
        public string RecipientCity { get; set; }                               //收件人城市
        public string RecipientPro { get; set; }                                //收件人省份
        public string RecipientAddress { get; set; }                         //收件详细地址
    }
}
