//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivestreamingE_commercePlatform.Models
{
    using System;
    using System.Collections.Generic;
    using Volo.Abp.Domain.Entities;
    using Volo.Abp.Domain.Entities.Auditing;

    //商品分类表
    public partial class GoodsClass: AuditedAggregateRoot<Guid>
    {
        public string ClassName { get; set; }                                                               //分类名称
        public Nullable<System.Guid> ClassPId { get; set; }                                     //父级Id
        public string ClassStatus { get; set; }                                                               //分类状态
        public Guid CategoryDelete { get; set; } //逻辑删除
    }
}
