//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivestreamingE_commercePlatform.Models
{
    using System;
    using System.Collections.Generic;
    using Volo.Abp.Domain.Entities;
    using Volo.Abp.Domain.Entities.Auditing;

    //商品表
    public partial class Goods:AuditedAggregateRoot<Guid>
    {
        public string GoodsName { get; set; }                           //商品名称
        public string GoodsDescribe { get; set; }                       //商品描述(富文本)
        public Nullable<System.Guid> ClassifiCationId { get; set; }            //分类Id
        public string GoodsStatus { get; set; }                                              //上下架状态
        public double GoodsPrice { get; set; }                                              //商品价格
        public double PreferentialPrice { get; set; }                                       //商品优惠价
        public Guid ProductDisplay { get; set; }   //逻辑删除
    }
}
