//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivestreamingE_commercePlatform.Models
{
    using System;
    using System.Collections.Generic;
    using Volo.Abp.Domain.Entities.Auditing;

    //会员表
    public partial class Members : AuditedAggregateRoot<Guid>
    {
        public string Memberslevel { get; set; }                                                      //会员等级
        public Nullable<System.DateTime> OverdueTime { get; set; }                //到期时间
        public Nullable<System.DateTime> OpenTime { get; set; }                     //开启时间
        public Nullable<System.Guid> UserId { get; set; }                                   //用户Id
    }
}
