//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivestreamingE_commercePlatform.Models
{
    using System;
    using System.Collections.Generic;
    using Volo.Abp.Domain.Entities.Auditing;

    //菜单表
    public partial class Menus : AuditedAggregateRoot<Guid>
    {
        public string MenuName { get; set; }                                               //菜单名称
        public string MenusUrl { get; set; }                                                  //菜单路径
        public Nullable<System.Guid> MenusPID { get; set; }                   //父级Id
    }
}
