//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivestreamingE_commercePlatform.Models
{
    using System;
    using System.Collections.Generic;
    using Volo.Abp.Domain.Entities.Auditing;

    //订单表
    public partial class OrderInfo : AuditedAggregateRoot<Guid>
    {
        public int OrderStatus { get; set; } = 0;                                                            //订单状态（已下单（未支付）0 ，待发货（已支付）10，已发货（待收货）20，已完成（已确认）30，订单取消（订单关闭）40）

        public string OrderNumber { get; set; }                                                        //订单编号(雪花)
        public Nullable<System.DateTime> OrderTime { get; set; } = DateTime.Now;                      //下订单时间
        public decimal commodCountPrice { get; set; }                                             //商品总金额
        public Nullable<double> SumMonery { get; set; }                                        //订单总金额
        public Nullable<double> AmountPay { get; set; }                                        //实付金额
        public string PayStatus { get; set; }                                                               //支付状态(已支付1，待支付0)
        public Nullable<System.Guid> UserId { get; set; }                                       //用户Id
        public Nullable<System.DateTime> PayTime { get; set; }                            //支付时间
        public int payWayInfoId { get; set; }                                                             //支付方式
    }
}
