//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivestreamingE_commercePlatform.Models
{
    using System;
    using System.Collections.Generic;
    using Volo.Abp.Domain.Entities.Auditing;

    //省市联动表
    public partial class ProCity: AuditedAggregateRoot<Guid>
    {
        public string City { get; set; }                                                    //城市
        public string Provinces { get; set; }                                           //省份
        public string Address { get; set; }                                              //详细地址
        public Nullable<System.Guid> PID { get; set; }                      //父级Id
    }
}
