//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivestreamingE_commercePlatform.Models
{
    using System;
    using System.Collections.Generic;
    using Volo.Abp.Domain.Entities.Auditing;

    //角色表
    public partial class Role : AuditedAggregateRoot<Guid>
    {
        public string RoleName { get; set; }                         //角色名称
        public string RoleDescribe { get; set; }                     //角色描述
        public string RoleStatus { get; set; }                         //角色状态
    }
}
