//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivestreamingE_commercePlatform.Models
{
    using System;
    using System.Collections.Generic;
    using Volo.Abp.Domain.Entities.Auditing;

    //用户表
    public partial class User: AuditedAggregateRoot<Guid>
    {
        public string Account { get; set; }      //登录名
        public string Password { get; set; }    //登录密码(MD5加密)
        public string LogStatus { get; set; }   //登录状态
        public Nullable<System.DateTime> LogTime { get; set; }   //登录时间
        public Nullable<System.DateTime> OutTime { get; set; }   //退出时间
        public string Phone { get; set; }         //手机号登录

        public DateTime UserslockLoginDate { get; set; } = DateTime.Now.AddDays(+2);      //锁定时间
        
        public bool UsersisDelete { get; set; } = false;     //是否锁定
       
        public int UsersSum { get; set; } = 0;                   //密码错误次数
    }
}
