//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivestreamingE_commercePlatform.Models
{
    using System;
    using System.Collections.Generic;
    using Volo.Abp.Domain.Entities.Auditing;

    //用户基本信息表
    public partial class UserInfo : AuditedAggregateRoot<Guid>
    {
        public string NickName { get; set; }                                                     //用户昵称
        public string Gender { get; set; }                                                           //性别
        public string Photo { get; set; }                                                                  //头像
        public string Email { get; set; }                                                              //邮箱
        public string Address { get; set; }                                                          //地址
        public string Phone { get; set; }                                                             //手机号
        public Nullable<System.Guid> LogUserId { get; set; }                        //用户登录外键
    }
}
